// <auto-generated />
using System;
using FatsitBikerMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FatsitBikerMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525021322_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FatsitBikerMVC.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FatsitBikerMVC.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Xe tay ga"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Xe số"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Xe côn tay"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Xe điện"
                        });
                });

            modelBuilder.Entity("FatsitBikerMVC.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Desc = "Mô tả chi tiết cho Honda SH 150i",
                            Engine = "125cc",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "Honda SH 150i",
                            Power = "10 HP",
                            Price = "34000000",
                            Weight = "110 kg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Desc = "Mô tả chi tiết cho Honda Vision",
                            Engine = "125cc",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "Honda Vision",
                            Power = "10 HP",
                            Price = "34000000",
                            Weight = "110 kg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Desc = "Mô tả chi tiết cho Honda Air Blade",
                            Engine = "125cc",
                            Images = "[\"https://images.unsplash.com/photo-1568772585407-9361f9bf3a87\",\"https://images.unsplash.com/photo-1558981359-219d6364c9c8\"]",
                            Name = "Honda Air Blade",
                            Power = "10 HP",
                            Price = "84000000",
                            Weight = "110 kg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Desc = "Mô tả chi tiết cho Honda Lead",
                            Engine = "125cc",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "Honda Lead",
                            Power = "10 HP",
                            Price = "65000000",
                            Weight = "110 kg"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Desc = "Mô tả chi tiết cho Honda Vario",
                            Engine = "125cc",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "Honda Vario",
                            Power = "10 HP",
                            Price = "85000000",
                            Weight = "110 kg"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Desc = "Mô tả chi tiết cho Yamaha NVX",
                            Engine = "125cc",
                            Images = "[\"https://images.unsplash.com/photo-1568772585407-9361f9bf3a87\",\"https://images.unsplash.com/photo-1558981359-219d6364c9c8\"]",
                            Name = "Yamaha NVX",
                            Power = "10 HP",
                            Price = "87000000",
                            Weight = "110 kg"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Desc = "Mô tả chi tiết cho Yamaha Grande",
                            Engine = "125cc",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "Yamaha Grande",
                            Power = "10 HP",
                            Price = "41000000",
                            Weight = "110 kg"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Desc = "Mô tả chi tiết cho Yamaha Latte",
                            Engine = "125cc",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "Yamaha Latte",
                            Power = "10 HP",
                            Price = "81000000",
                            Weight = "110 kg"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Desc = "Mô tả chi tiết cho Yamaha FreeGo",
                            Engine = "125cc",
                            Images = "[\"https://images.unsplash.com/photo-1568772585407-9361f9bf3a87\",\"https://images.unsplash.com/photo-1558981359-219d6364c9c8\"]",
                            Name = "Yamaha FreeGo",
                            Power = "10 HP",
                            Price = "48000000",
                            Weight = "110 kg"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Desc = "Mô tả chi tiết cho Vespa Sprint",
                            Engine = "125cc",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "Vespa Sprint",
                            Power = "10 HP",
                            Price = "65000000",
                            Weight = "110 kg"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Desc = "Mô tả chi tiết cho Vespa Primavera",
                            Engine = "125cc",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "Vespa Primavera",
                            Power = "10 HP",
                            Price = "46000000",
                            Weight = "110 kg"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Desc = "Mô tả chi tiết cho Piaggio Medley",
                            Engine = "125cc",
                            Images = "[\"https://images.unsplash.com/photo-1568772585407-9361f9bf3a87\",\"https://images.unsplash.com/photo-1558981359-219d6364c9c8\"]",
                            Name = "Piaggio Medley",
                            Power = "10 HP",
                            Price = "57000000",
                            Weight = "110 kg"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Desc = "Mô tả chi tiết cho Piaggio Liberty",
                            Engine = "125cc",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "Piaggio Liberty",
                            Power = "10 HP",
                            Price = "45000000",
                            Weight = "110 kg"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Desc = "Mô tả chi tiết cho Honda Wave Alpha",
                            Engine = "110cc",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "Honda Wave Alpha",
                            Power = "8 HP",
                            Price = "15000000",
                            Weight = "95 kg"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Desc = "Mô tả chi tiết cho Honda Wave RSX",
                            Engine = "110cc",
                            Images = "[\"https://images.unsplash.com/photo-1568772585407-9361f9bf3a87\",\"https://images.unsplash.com/photo-1558981359-219d6364c9c8\"]",
                            Name = "Honda Wave RSX",
                            Power = "8 HP",
                            Price = "18000000",
                            Weight = "95 kg"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Desc = "Mô tả chi tiết cho Honda Blade",
                            Engine = "110cc",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "Honda Blade",
                            Power = "8 HP",
                            Price = "33000000",
                            Weight = "95 kg"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Desc = "Mô tả chi tiết cho Honda Future",
                            Engine = "110cc",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "Honda Future",
                            Power = "8 HP",
                            Price = "19000000",
                            Weight = "95 kg"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Desc = "Mô tả chi tiết cho Yamaha Sirius",
                            Engine = "110cc",
                            Images = "[\"https://images.unsplash.com/photo-1568772585407-9361f9bf3a87\",\"https://images.unsplash.com/photo-1558981359-219d6364c9c8\"]",
                            Name = "Yamaha Sirius",
                            Power = "8 HP",
                            Price = "37000000",
                            Weight = "95 kg"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Desc = "Mô tả chi tiết cho Yamaha Jupiter",
                            Engine = "110cc",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "Yamaha Jupiter",
                            Power = "8 HP",
                            Price = "36000000",
                            Weight = "95 kg"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Desc = "Mô tả chi tiết cho SYM Elegant",
                            Engine = "110cc",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "SYM Elegant",
                            Power = "8 HP",
                            Price = "23000000",
                            Weight = "95 kg"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Desc = "Mô tả chi tiết cho SYM Galaxy",
                            Engine = "110cc",
                            Images = "[\"https://images.unsplash.com/photo-1568772585407-9361f9bf3a87\",\"https://images.unsplash.com/photo-1558981359-219d6364c9c8\"]",
                            Name = "SYM Galaxy",
                            Power = "8 HP",
                            Price = "17000000",
                            Weight = "95 kg"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Desc = "Mô tả chi tiết cho Honda Super Cub",
                            Engine = "110cc",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "Honda Super Cub",
                            Power = "8 HP",
                            Price = "28000000",
                            Weight = "95 kg"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Desc = "Mô tả chi tiết cho Yamaha Finn",
                            Engine = "110cc",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "Yamaha Finn",
                            Power = "8 HP",
                            Price = "23000000",
                            Weight = "95 kg"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Desc = "Mô tả chi tiết cho SYM Angela",
                            Engine = "110cc",
                            Images = "[\"https://images.unsplash.com/photo-1568772585407-9361f9bf3a87\",\"https://images.unsplash.com/photo-1558981359-219d6364c9c8\"]",
                            Name = "SYM Angela",
                            Power = "8 HP",
                            Price = "32000000",
                            Weight = "95 kg"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Desc = "Mô tả chi tiết cho SYM Star SR",
                            Engine = "110cc",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "SYM Star SR",
                            Power = "8 HP",
                            Price = "29000000",
                            Weight = "95 kg"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Desc = "Mô tả chi tiết cho Yamaha Exciter 155",
                            Engine = "150cc - 1000cc",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "Yamaha Exciter 155",
                            Power = "15 - 200 HP",
                            Price = "327000000",
                            Weight = "130 - 200 kg"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Desc = "Mô tả chi tiết cho Honda Winner X",
                            Engine = "150cc - 1000cc",
                            Images = "[\"https://images.unsplash.com/photo-1568772585407-9361f9bf3a87\",\"https://images.unsplash.com/photo-1558981359-219d6364c9c8\"]",
                            Name = "Honda Winner X",
                            Power = "15 - 200 HP",
                            Price = "378000000",
                            Weight = "130 - 200 kg"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Desc = "Mô tả chi tiết cho Suzuki Raider",
                            Engine = "150cc - 1000cc",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "Suzuki Raider",
                            Power = "15 - 200 HP",
                            Price = "385000000",
                            Weight = "130 - 200 kg"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Desc = "Mô tả chi tiết cho Suzuki Satria",
                            Engine = "150cc - 1000cc",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "Suzuki Satria",
                            Power = "15 - 200 HP",
                            Price = "225000000",
                            Weight = "130 - 200 kg"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Desc = "Mô tả chi tiết cho Yamaha MT-15",
                            Engine = "150cc - 1000cc",
                            Images = "[\"https://images.unsplash.com/photo-1568772585407-9361f9bf3a87\",\"https://images.unsplash.com/photo-1558981359-219d6364c9c8\"]",
                            Name = "Yamaha MT-15",
                            Power = "15 - 200 HP",
                            Price = "156000000",
                            Weight = "130 - 200 kg"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            Desc = "Mô tả chi tiết cho Honda CBR150R",
                            Engine = "150cc - 1000cc",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "Honda CBR150R",
                            Power = "15 - 200 HP",
                            Price = "357000000",
                            Weight = "130 - 200 kg"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Desc = "Mô tả chi tiết cho Yamaha R15",
                            Engine = "150cc - 1000cc",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "Yamaha R15",
                            Power = "15 - 200 HP",
                            Price = "140000000",
                            Weight = "130 - 200 kg"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            Desc = "Mô tả chi tiết cho Suzuki GSX-R150",
                            Engine = "150cc - 1000cc",
                            Images = "[\"https://images.unsplash.com/photo-1568772585407-9361f9bf3a87\",\"https://images.unsplash.com/photo-1558981359-219d6364c9c8\"]",
                            Name = "Suzuki GSX-R150",
                            Power = "15 - 200 HP",
                            Price = "280000000",
                            Weight = "130 - 200 kg"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            Desc = "Mô tả chi tiết cho Honda MSX 125",
                            Engine = "150cc - 1000cc",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "Honda MSX 125",
                            Power = "15 - 200 HP",
                            Price = "265000000",
                            Weight = "130 - 200 kg"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            Desc = "Mô tả chi tiết cho Kawasaki Z1000",
                            Engine = "150cc - 1000cc",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "Kawasaki Z1000",
                            Power = "15 - 200 HP",
                            Price = "160000000",
                            Weight = "130 - 200 kg"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Desc = "Mô tả chi tiết cho Ducati Panigale",
                            Engine = "150cc - 1000cc",
                            Images = "[\"https://images.unsplash.com/photo-1568772585407-9361f9bf3a87\",\"https://images.unsplash.com/photo-1558981359-219d6364c9c8\"]",
                            Name = "Ducati Panigale",
                            Power = "15 - 200 HP",
                            Price = "395000000",
                            Weight = "130 - 200 kg"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            Desc = "Mô tả chi tiết cho Yamaha MT-09",
                            Engine = "150cc - 1000cc",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "Yamaha MT-09",
                            Power = "15 - 200 HP",
                            Price = "46000000",
                            Weight = "130 - 200 kg"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Desc = "Mô tả chi tiết cho VinFast Feliz S",
                            Engine = "Điện",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "VinFast Feliz S",
                            Power = "1000W - 3000W",
                            Price = "41000000",
                            Weight = "90 - 120 kg"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Desc = "Mô tả chi tiết cho VinFast Klara S",
                            Engine = "Điện",
                            Images = "[\"https://images.unsplash.com/photo-1568772585407-9361f9bf3a87\",\"https://images.unsplash.com/photo-1558981359-219d6364c9c8\"]",
                            Name = "VinFast Klara S",
                            Power = "1000W - 3000W",
                            Price = "39000000",
                            Weight = "90 - 120 kg"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Desc = "Mô tả chi tiết cho VinFast Vento S",
                            Engine = "Điện",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "VinFast Vento S",
                            Power = "1000W - 3000W",
                            Price = "41000000",
                            Weight = "90 - 120 kg"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Desc = "Mô tả chi tiết cho VinFast Theon S",
                            Engine = "Điện",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "VinFast Theon S",
                            Power = "1000W - 3000W",
                            Price = "54000000",
                            Weight = "90 - 120 kg"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            Desc = "Mô tả chi tiết cho VinFast Evo 200",
                            Engine = "Điện",
                            Images = "[\"https://images.unsplash.com/photo-1568772585407-9361f9bf3a87\",\"https://images.unsplash.com/photo-1558981359-219d6364c9c8\"]",
                            Name = "VinFast Evo 200",
                            Power = "1000W - 3000W",
                            Price = "39000000",
                            Weight = "90 - 120 kg"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            Desc = "Mô tả chi tiết cho Yadea Odora",
                            Engine = "Điện",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "Yadea Odora",
                            Power = "1000W - 3000W",
                            Price = "29000000",
                            Weight = "90 - 120 kg"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            Desc = "Mô tả chi tiết cho Yadea Xmen",
                            Engine = "Điện",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "Yadea Xmen",
                            Power = "1000W - 3000W",
                            Price = "30000000",
                            Weight = "90 - 120 kg"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 4,
                            Desc = "Mô tả chi tiết cho Pega S",
                            Engine = "Điện",
                            Images = "[\"https://images.unsplash.com/photo-1568772585407-9361f9bf3a87\",\"https://images.unsplash.com/photo-1558981359-219d6364c9c8\"]",
                            Name = "Pega S",
                            Power = "1000W - 3000W",
                            Price = "49000000",
                            Weight = "90 - 120 kg"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            Desc = "Mô tả chi tiết cho Dat Bike Weaver",
                            Engine = "Điện",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "Dat Bike Weaver",
                            Power = "1000W - 3000W",
                            Price = "31000000",
                            Weight = "90 - 120 kg"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            Desc = "Mô tả chi tiết cho Dat Bike Weaver 200",
                            Engine = "Điện",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "Dat Bike Weaver 200",
                            Power = "1000W - 3000W",
                            Price = "35000000",
                            Weight = "90 - 120 kg"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            Desc = "Mô tả chi tiết cho Dat Bike Weaver++",
                            Engine = "Điện",
                            Images = "[\"https://images.unsplash.com/photo-1568772585407-9361f9bf3a87\",\"https://images.unsplash.com/photo-1558981359-219d6364c9c8\"]",
                            Name = "Dat Bike Weaver++",
                            Power = "1000W - 3000W",
                            Price = "61000000",
                            Weight = "90 - 120 kg"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 4,
                            Desc = "Mô tả chi tiết cho Yadea Ulike",
                            Engine = "Điện",
                            Images = "[\"https://images.unsplash.com/photo-1449426468159-d96dbf08f19f\",\"https://images.unsplash.com/photo-1615172282427-9a57ef2d142e\"]",
                            Name = "Yadea Ulike",
                            Power = "1000W - 3000W",
                            Price = "24000000",
                            Weight = "90 - 120 kg"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 4,
                            Desc = "Mô tả chi tiết cho Dibao Gogo",
                            Engine = "Điện",
                            Images = "[\"https://images.unsplash.com/photo-1558981403-c5f9899a28bc\",\"https://images.unsplash.com/photo-1558980394-0a37b363a516\"]",
                            Name = "Dibao Gogo",
                            Power = "1000W - 3000W",
                            Price = "61000000",
                            Weight = "90 - 120 kg"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FatsitBikerMVC.Models.Product", b =>
                {
                    b.HasOne("FatsitBikerMVC.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FatsitBikerMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FatsitBikerMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FatsitBikerMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FatsitBikerMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FatsitBikerMVC.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
